#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gnome-maps
Version  : 3.38.0
Release  : 29
URL      : https://download.gnome.org/sources/gnome-maps/3.38/gnome-maps-3.38.0.tar.xz
Source0  : https://download.gnome.org/sources/gnome-maps/3.38/gnome-maps-3.38.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 HPND LGPL-3.0 WTFPL
Requires: gnome-maps-bin = %{version}-%{release}
Requires: gnome-maps-data = %{version}-%{release}
Requires: gnome-maps-lib = %{version}-%{release}
Requires: gnome-maps-license = %{version}-%{release}
Requires: gnome-maps-locales = %{version}-%{release}
BuildRequires : appstream-glib
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : folks-dev
BuildRequires : geoclue-dev
BuildRequires : geocode-glib-dev
BuildRequires : libchamplain-dev
BuildRequires : libgee-dev
BuildRequires : pkgconfig(champlain-0.12)
BuildRequires : pkgconfig(folks)
BuildRequires : pkgconfig(gee-0.8)
BuildRequires : pkgconfig(geoclue-2.0)
BuildRequires : pkgconfig(geocode-glib-1.0)
BuildRequires : pkgconfig(gjs-1.0)
BuildRequires : pkgconfig(rest-0.7)
BuildRequires : rest-dev

%description
Maps is a map application for GNOME.
More information on https://wiki.gnome.org/Apps/Maps

%package bin
Summary: bin components for the gnome-maps package.
Group: Binaries
Requires: gnome-maps-data = %{version}-%{release}
Requires: gnome-maps-license = %{version}-%{release}

%description bin
bin components for the gnome-maps package.


%package data
Summary: data components for the gnome-maps package.
Group: Data

%description data
data components for the gnome-maps package.


%package lib
Summary: lib components for the gnome-maps package.
Group: Libraries
Requires: gnome-maps-data = %{version}-%{release}
Requires: gnome-maps-license = %{version}-%{release}

%description lib
lib components for the gnome-maps package.


%package license
Summary: license components for the gnome-maps package.
Group: Default

%description license
license components for the gnome-maps package.


%package locales
Summary: locales components for the gnome-maps package.
Group: Default

%description locales
locales components for the gnome-maps package.


%prep
%setup -q -n gnome-maps-3.38.0
cd %{_builddir}/gnome-maps-3.38.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1600319166
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir || :

%install
mkdir -p %{buildroot}/usr/share/package-licenses/gnome-maps
cp %{_builddir}/gnome-maps-3.38.0/COPYING %{buildroot}/usr/share/package-licenses/gnome-maps/23e13f8d523ce36d2547861c333e8e9c269f4c1a
cp %{_builddir}/gnome-maps-3.38.0/src/geojson-vt/LICENSE %{buildroot}/usr/share/package-licenses/gnome-maps/d59bb6ceea36fb0c66ed07ec231b74ecff15c94b
cp %{_builddir}/gnome-maps-3.38.0/src/togeojson/LICENSE %{buildroot}/usr/share/package-licenses/gnome-maps/af2a0e22eb18bfd67ae71eab3f5e85853a489ed0
cp %{_builddir}/gnome-maps-3.38.0/src/xmldom/LICENSE %{buildroot}/usr/share/package-licenses/gnome-maps/7079d60a22e0c83a63c2956ee65cb367af261521
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang gnome-maps

%files
%defattr(-,root,root,-)
/usr/lib64/gnome-maps/girepository-1.0/GnomeMaps-1.0.typelib

%files bin
%defattr(-,root,root,-)
/usr/bin/gnome-maps

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.gnome.Maps.desktop
/usr/share/dbus-1/services/org.gnome.Maps.service
/usr/share/glib-2.0/schemas/org.gnome.Maps.gschema.xml
/usr/share/gnome-maps/gir-1.0/GnomeMaps-1.0.gir
/usr/share/gnome-maps/icons/hicolor/16x16/apps/layer-not-visible-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/16x16/apps/layer-visible-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/16x16/apps/layers-button-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/16x16/apps/maps-point-end-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/16x16/apps/maps-point-end.svg
/usr/share/gnome-maps/icons/hicolor/16x16/apps/maps-point-start-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/16x16/apps/maps-point-start.svg
/usr/share/gnome-maps/icons/hicolor/16x16/apps/route-bike-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/16x16/apps/route-button-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/16x16/apps/route-car-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/16x16/apps/route-pedestrian-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/16x16/apps/route-reverse-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/16x16/apps/route-transit-airplane-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/16x16/apps/route-transit-bus-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/16x16/apps/route-transit-cablecar-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/16x16/apps/route-transit-ferry-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/16x16/apps/route-transit-funicular-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/16x16/apps/route-transit-gondolalift-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/16x16/apps/route-transit-subway-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/16x16/apps/route-transit-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/16x16/apps/route-transit-train-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/16x16/apps/route-transit-tram-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/24x24/apps/user-location-compass.png
/usr/share/gnome-maps/icons/hicolor/24x24/apps/user-location.png
/usr/share/gnome-maps/icons/hicolor/32x32/apps/maps-direction-continue-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/32x32/apps/maps-direction-elevator-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/32x32/apps/maps-direction-left-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/32x32/apps/maps-direction-right-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/32x32/apps/maps-direction-roundabout-0-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/32x32/apps/maps-direction-roundabout-135-lht-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/32x32/apps/maps-direction-roundabout-135-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/32x32/apps/maps-direction-roundabout-180-lht-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/32x32/apps/maps-direction-roundabout-180-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/32x32/apps/maps-direction-roundabout-225-lht-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/32x32/apps/maps-direction-roundabout-225-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/32x32/apps/maps-direction-roundabout-270-lht-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/32x32/apps/maps-direction-roundabout-270-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/32x32/apps/maps-direction-roundabout-315-lht-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/32x32/apps/maps-direction-roundabout-315-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/32x32/apps/maps-direction-roundabout-45-lht-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/32x32/apps/maps-direction-roundabout-45-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/32x32/apps/maps-direction-roundabout-90-lht-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/32x32/apps/maps-direction-roundabout-90-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/32x32/apps/maps-direction-roundabout-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/32x32/apps/maps-direction-sharpleft-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/32x32/apps/maps-direction-sharpright-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/32x32/apps/maps-direction-slightleft-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/32x32/apps/maps-direction-slightright-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/32x32/apps/maps-direction-u-turn-left-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/32x32/apps/maps-direction-u-turn-right-symbolic.svg
/usr/share/gnome-maps/icons/hicolor/32x32/apps/mark-location.png
/usr/share/gnome-maps/maps-service.json
/usr/share/gnome-maps/org.gnome.Maps
/usr/share/gnome-maps/org.gnome.Maps.data.gresource
/usr/share/gnome-maps/org.gnome.Maps.src.gresource
/usr/share/icons/hicolor/scalable/apps/org.gnome.Maps.Devel.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Maps.svg
/usr/share/icons/hicolor/symbolic/apps/org.gnome.Maps-symbolic.svg
/usr/share/metainfo/org.gnome.Maps.appdata.xml

%files lib
%defattr(-,root,root,-)
/usr/lib64/gnome-maps/libgnome-maps.so
/usr/lib64/gnome-maps/libgnome-maps.so.0
/usr/lib64/gnome-maps/libgnome-maps.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gnome-maps/23e13f8d523ce36d2547861c333e8e9c269f4c1a
/usr/share/package-licenses/gnome-maps/7079d60a22e0c83a63c2956ee65cb367af261521
/usr/share/package-licenses/gnome-maps/af2a0e22eb18bfd67ae71eab3f5e85853a489ed0
/usr/share/package-licenses/gnome-maps/d59bb6ceea36fb0c66ed07ec231b74ecff15c94b

%files locales -f gnome-maps.lang
%defattr(-,root,root,-)

